#!/bin/bash

name=$1
declare -a windowID=($(gdbus call --session --dest org.wayland.compositor --object-path /org/wayland/compositor --method org.wayland.compositor.query_view_vector_taskman_ids | sed 's/uint32//; s/[^[:digit:]]/ /g; s/  */ /g; s/^  *//g'))
declare -a windowAppUnsorted=()
declare -a windows=()
for i in "${windowID[@]}"
do
    windowAppUnsorted+=("$(gdbus call --session --dest org.wayland.compositor --object-path /org/wayland/compositor --method org.wayland.compositor.query_view_app_id "$i" | awk -F\' '{print $2}')":"'"$i"'") 
done
printf '%s\n' "${windowAppUnsorted[@]}" | grep $1 | awk -F\' '{print $2}' | sed 's/\n/ /g' | jq -R . | jq -s .